apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
#  - hostmount-anyuid 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
subjects:
- kind: ServiceAccount
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
userNames:
- system:serviceaccount:{{.SpecialResource.Spec.Namespace}}:{.HardwareResource}}-{{.GroupName.DeviceFeatureDiscovery}}
--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
  annotations:
    specialresource.openshift.io/wait: "true"
  labels:
    app.kubernetes.io/name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
    app.kubernetes.io/version: 1.0.0-alpha
    app.kubernetes.io/part-of: nvidia-gpu
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
      app.kubernetes.io/part-of: nvidia-gpu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
        app.kubernetes.io/version: 1.0.0-alpha
        app.kubernetes.io/part-of: nvidia-gpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{.StateName.DeviceMonitoring}}-{{.SpecialResource.Name}}
                operator: In 
                values:
                - ready 
      tolerations:
        - operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
      effect: NoSchedule
      serviceAccount: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
      serviceAccountName: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
      containers:
        - image: nvidia/gpu-feature-discovery:v0.2.0
          name: {{.SpecialResource.Name}}-{{.GroupName.DeviceFeatureDiscovery}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-product-name
              mountPath: "/sys/class/dmi/id/product_name"
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        {{.SpecialResource.Spec.Node.Selector}}: "true" 