{
 "title": "GPU",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_fb_used" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_utilization" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_power_usage" }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_temp" }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_sm_clock" }
   ]
  },
  {
   "title": "GPU Thermal Violation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dcgm_thermal_violation" }
   ]
  }
 ]
}